name: Precache Codespace
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codespaces-precache@v1-stable
        with:
          regions: WestEurope
          sku_name: premiumLinux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
